In [18]:
from typing import Optional
from pathlib import Path

import pandas as pd

### Explore

In [14]:
df = pd.read_feather(Path("../data/7-eco/joined-counts/ecotypes-joined-counts.part.8.feather"))
df.shape

(23871866, 8)

In [15]:
df.fillna(0, inplace=True)

In [16]:
df.head()

,cvi,sha,c24,eri,ler,an1,kyo,col
kmer,,,,,,,,
AAAAAAAAAAAAAAAAAAAAAAG,30429.0,32880.0,21573.0,15679.0,25477.0,38098.0,15211.0,9660.0
AAAAAAAAAAAAAAAAAAAAGCA,8202.0,1102.0,570.0,568.0,1014.0,1108.0,607.0,443.0
AAAAAAAAAAAAAAAAAAAATAA,3986.0,3833.0,2710.0,2705.0,4140.0,6612.0,2693.0,643.0
AAAAAAAAAAAAAAAAAAACAAC,634.0,695.0,542.0,485.0,734.0,795.0,449.0,249.0
AAAAAAAAAAAAAAAAAAACACA,933.0,980.0,702.0,610.0,1050.0,961.0,648.0,354.0

In [17]:
df = df[(df == 0).sum(axis=1) > 0]
df.shape

(15640640, 8)

In [13]:
df.head()

                          cvi   sha   c24   eri   ler   an1   kyo  col
kmer
AAAAAAAAAAAAAAAAAACCGCT  42.0  30.0  17.0  27.0  47.0  26.0  23.0  0.0
AAAAAAAAAAAAAAAAAACGAGC  21.0  15.0  11.0  16.0  13.0  27.0  23.0  0.0
AAAAAAAAAAAAAAAAAACGCGT  10.0   0.0   8.0   0.0  23.0   0.0   0.0  0.0
AAAAAAAAAAAAAAAAAACGGGC  23.0  28.0  20.0  17.0  18.0  22.0  20.0  0.0
AAAAAAAAAAAAAAAAAAGCAGG  43.0  26.0  21.0  19.0  24.0  19.0   0.0  0.0

### Get Differential K-mers

In [19]:
df_diff: Optional[pd.DataFrame] = None

for path in Path("../data/7-eco/joined-counts/").glob("*.part.*.feather"):
    print(path)
    part = pd.read_feather(path)
    print(part.shape)
    part.fillna(0, inplace=True)
    part = part[(part == 0).sum(axis=1) > 0]
    print(part.shape)

    if df_diff is None:
        df_diff = part
    else:
        df_diff = pd.concat([df_diff, part])

assert df_diff is not None

df_diff.shape

../data/7-eco/joined-counts/ecotypes-joined-counts.part.4.feather
(23861079, 8)
(15633580, 8)
../data/7-eco/joined-counts/ecotypes-joined-counts.part.8.feather
(23871866, 8)
(15640640, 8)
../data/7-eco/joined-counts/ecotypes-joined-counts.part.5.feather
(23866540, 8)
(15634335, 8)
../data/7-eco/joined-counts/ecotypes-joined-counts.part.3.feather
(23855233, 8)
(15630104, 8)
../data/7-eco/joined-counts/ecotypes-joined-counts.part.6.feather
(23870931, 8)
(15638797, 8)
../data/7-eco/joined-counts/ecotypes-joined-counts.part.7.feather
(23863841, 8)
(15634344, 8)
../data/7-eco/joined-counts/ecotypes-joined-counts.part.2.feather
(23873594, 8)
(15643337, 8)
../data/7-eco/joined-counts/ecotypes-joined-counts.part.1.feather
(23872354, 8)
(15641155, 8)

(125096292, 8)

In [20]:
df_diff.head()

                           cvi   sha   c24   eri    ler   an1   kyo   col
kmer
AAAAAAAAAAAAAAAAAACACGG   20.0  35.0  34.0  28.0   50.0  56.0  30.0   0.0
AAAAAAAAAAAAAAAAAACATGC   59.0  68.0  32.0  44.0   26.0  78.0  28.0   0.0
AAAAAAAAAAAAAAAAAACCCGG   94.0  66.0  54.0  43.0   62.0  84.0  44.0   0.0
AAAAAAAAAAAAAAAAAACCGCC  102.0  59.0  53.0  62.0  100.0  99.0  40.0   0.0
AAAAAAAAAAAAAAAAAACCGTA   10.0  26.0  40.0  28.0   16.0  58.0   0.0  26.0

In [21]:
df_diff.to_feather(Path("../data/7-eco/ecotypes-joined-counts-diff.feather"), compression="zstd", compression_level=8)

### Join Kmers with Hamburg

In [22]:
df_hamburg = pd.read_feather(Path("../data/hamburg/correlations/inner-joined-corr.feather"))
df_hamburg.shape

(31269324, 30)

In [23]:
df_hamburg.head()

,1_Col_ColLer,2_Col_ColLer,3_Col_ColLer,4_Col_ColLer,5_Col_ColLer,1_Col_tColaLer,2_Col_tColaLer,3_Col_tColaLer,4_Col_tColaLer,5_Col_tColaLer,...,1_Col_aColaLer,2_Col_aColaLer,3_Col_aColaLer,4_Col_aColaLer,5_Col_aColaLer,1_tColaLer_Col,2_tColaLer_Col,3_tColaLer_Col,4_tColaLer_Col,5_tColaLer_Col
kmer,,,,,,,,,,,,,,,,,,,,,
AAAAAAAAAAAAAAAAAAAAAAG,0.007635,0.037383,-0.080028,-0.470359,-0.095074,0.033120,0.135064,0.022142,-0.327344,-0.073923,...,0.074363,0.017635,-0.049185,-0.320848,-0.109882,0.047928,0.065671,-0.228059,-0.513192,0.029645
AAAAAAAAAAAAAAAAAAAAAAT,0.095866,-0.032075,-0.163477,-0.035904,-0.214911,-0.152069,-0.003365,0.069211,0.045978,0.114569,...,0.031427,0.109156,0.166566,0.049958,-0.180966,-0.049987,0.054018,-0.099995,-0.084989,-0.158841
AAAAAAAAAAAAAAAAAAAAACG,0.062797,-0.067435,0.083978,0.001512,-0.026108,0.062035,0.051977,-0.083720,0.134239,-0.042184,...,0.052469,-0.144262,0.022753,0.167928,0.188214,0.139604,0.013748,-0.076922,-0.008543,0.077288
AAAAAAAAAAAAAAAAAAAAAGG,-0.069464,-0.067622,-0.049354,-0.472716,-0.068523,0.148429,0.114371,0.048918,-0.414792,-0.060706,...,0.047029,0.040109,-0.080335,-0.255015,-0.126888,0.109252,0.197455,-0.097247,-0.460709,-0.078425
AAAAAAAAAAAAAAAAAAAAATT,0.046433,-0.024341,-0.170101,0.122011,-0.097482,-0.066154,0.037764,0.027342,0.033901,0.088831,...,-0.035078,0.064911,0.117439,0.066153,-0.136237,-0.201856,0.031117,-0.058155,-0.082085,-0.042770

In [24]:
df_joined: Optional[pd.DataFrame] = None

for path in Path("../data/7-eco/joined-counts/").glob("*.part.*.feather"):
    print(path)
    part = pd.read_feather(path)
    print(part.shape)
    part.fillna(0, inplace=True)
    part = part[part.index.isin(df_hamburg.index)]
    print(part.shape)

    if df_joined is None:
        df_joined = part
    else:
        df_joined = pd.concat([df_joined, part])

assert df_joined is not None

df_joined.shape

../data/7-eco/joined-counts/ecotypes-joined-counts.part.4.feather
(23861079, 8)
(3856464, 8)
../data/7-eco/joined-counts/ecotypes-joined-counts.part.8.feather
(23871866, 8)
(3856507, 8)
../data/7-eco/joined-counts/ecotypes-joined-counts.part.5.feather
(23866540, 8)
(3857735, 8)
../data/7-eco/joined-counts/ecotypes-joined-counts.part.3.feather
(23855233, 8)
(3855309, 8)
../data/7-eco/joined-counts/ecotypes-joined-counts.part.6.feather
(23870931, 8)
(3853248, 8)
../data/7-eco/joined-counts/ecotypes-joined-counts.part.7.feather
(23863841, 8)
(3854778, 8)
../data/7-eco/joined-counts/ecotypes-joined-counts.part.2.feather
(23873594, 8)
(3855344, 8)
../data/7-eco/joined-counts/ecotypes-joined-counts.part.1.feather
(23872354, 8)
(3856685, 8)

(30846070, 8)

In [25]:
df_joined.to_feather(Path("../data/7-eco/ecotypes-joined-counts-hamburg.feather"), compression="zstd", compression_level=8)